baseURL = "https://crispinread.github.io/starb/"
languageCode = "en-us"
title = "St Arbuq as test Hugo Site"
AuthorName = "Paul Stanbridge"
publishDir = "docs"
Tagline = "Hello, new world!"
SocialLinks = "true"
theme = "hugo-uno"
